### PR TITLE
feat: move history into state

### LINKED ISSUE #20: Feature Request / Question - Possibility to see differences of Undo / Redo within an Effect
Hi Nils,

I'm fairly new to the whole concept of ngrx, immer.js and wieder.js so sorry in advance if this does not really concern wieder.js and can be solved otherwise.
I'd like to access the changes reversed or re-reapplied in an ngrx effect in order to reflect the undone/redone changes within a database. Reapplying the whole context would be possible, but a huge performance impact when there's only one object that needs to be adjusted.

Is there a possiblity that the Undo/Redo actions can put out the applied changes to an effect or that these differences can be accessed somehow?

### PR DESCRIPTION
**Pull request by nilsmehlhorn**
- manage undo-redo state inside store
- replace tracking with selectors

Closes #20 

Biggest part is done, open considerations: 
- [x] currently whole actions are stored with steps, maybe only store type and/or make configurable
- [x] action merging currently overrides action type with newly merge action; will that produce problems?
- [x] test selectors
- [x] should history be stored next to state? this might make it hard to select the state without history; maybe prefer an approach where state has sub-properties, e.g `{histories: Histories, state: S}`? Otherwise consider marking history as read-only.

### CODE REVIEW

**Comment by julianpoemp** [comment]
I tried to apply this build to the stackblitz example. Because there is no public build I created a test-repository and adapted the code as far as I can: https://github.com/julianpoemp/ngrx-wieder-test

It works if I don't use selectors. I don't understand how to use the createHistorySelectors method. Can you please explain how to use this method? You can find the problematic code here:
https://github.com/julianpoemp/ngrx-wieder-test/blob/5effd09daa2d118a52f2f632d184b1926ee1de95/src/app/app.component.ts#L40

Can you please explain how the key of History is generated? In the stackblitz example the key is as equal as the id of a list. How is this possible if it's not defined anywhere? (as far as I can see)

**Comment by nilsmehlhorn** [comment]
> I tried to apply this build to the stackblitz example. Because there is no public build I created a test-repository and adapted the code as far as I can: https://github.com/julianpoemp/ngrx-wieder-test

The StackBlitz example is based on this repository: https://github.com/nilsmehlhorn/ngrx-wieder-example
You could checkout the branch for this PR, build it, then checkout ngrx-wieder-example and [link](https://docs.npmjs.com/cli/v6/commands/npm-link) the build - that's how I verify things, haven't done that for the PR yet. You can also link the build to any other application that relies on ngrx-wieder.

> It works if I don't use selectors. I don't understand the createHistorySelectors method. Can you please explain how to use this method?

I didn't test the selectors yet, but they're meant to work like this:
```typescript
import {createHistorySelectors} from 'ngrx-wieder';

// initialize selectors, because the lib can't know where your undoable state is
// (this is similar to how you'd do it with @ngrx/entity)
const {selectCanUndo, selectCanRedo} = createHistorySelectors(state => state.app)
// pass initialized selectors to store to create selection observable
// optionally pass history key as props, otherwise default is used
// (maybe there should be selectors for getting the active history based on the segmenter?)
const canUndo$ = this.store.select(selectCanUndo)
const canRedo$ = this.store.select(selectCanRedo)
```

> Can you please explain how the key of History is generated? In the stackblitz example the key is as equal as the id of a list. How is this possible if it's not defined anywhere? (as far as I can see)

The history key is used for [segmentation](https://github.com/nilsmehlhorn/ngrx-wieder#segmentation), by default it's `"DEFAULT"`, as you can see [here](https://github.com/nilsmehlhorn/ngrx-wieder/blob/de6d6048a1e4b4cd492f0ec930b50d42fd0e1da6/projects/ngrx-wieder/src/lib/undo-redo.reducer.ts#L94) for the current release and [here](https://github.com/nilsmehlhorn/ngrx-wieder/blob/d9a3ceb66f55a46da98961a19586af4149fdba5b/projects/ngrx-wieder/src/lib/undo-redo.reducer.ts#L81) in the PR. For the example, the key generation is overriden to use the list ID ([here](https://github.com/nilsmehlhorn/ngrx-wieder-example/blob/df086f81a23222040db69b5e64f34e07e64baac7/src/app/on.reducer.ts#L21) in the example repo, [here](https://github.com/julianpoemp/ngrx-wieder-test/blob/5053554b2be0d3e058f57ca630ae48779ec1debe/src/app/on.reducer.ts#L21) in your repo) to facilitate different histories for each list.

**Comment by julianpoemp** [comment]
> The StackBlitz example is based on this repository: https://github.com/nilsmehlhorn/ngrx-wieder-example
You could checkout the branch for this PR, build it, then checkout ngrx-wieder-example and link the build - that's how I verify things, haven't done that for the PR yet. You can also link the build to any other application that relies on ngrx-wieder.

good to know, thanks!

> I didn't test the selectors yet, but they're meant to work like this:

I inserted your code in my repository ([here](https://github.com/julianpoemp/ngrx-wieder-test/blob/69fae1cb4bc859fc33728cebb1c8139a8184dffd/src/app/app.component.ts#L40)), but unfortunately it's not working:
`core.js:5980 ERROR TypeError: Cannot read property 'undoable' of undefined`. The error occurs [here](https://github.com/nilsmehlhorn/ngrx-wieder/blob/d9a3ceb66f55a46da98961a19586af4149fdba5b/projects/ngrx-wieder/src/lib/undo-redo.selectors.ts#L12).
I figured out, that the key in that line is still "DEFAULT" but not the key of the active list. I have still defined the segmenter [here](https://github.com/julianpoemp/ngrx-wieder-test/blob/69fae1cb4bc859fc33728cebb1c8139a8184dffd/src/app/on.reducer.ts#L21) Is this a bug in the library or did I do something wrong?

> The history key is used for segmentation, by default it's "DEFAULT", as you can see here for the current release and here in the PR. For the example, the key generation is overriden to use the list ID (here in the example repo, here in your repo) to facilitate different histories for each list.

my bad, I should have read the section about segments, sorry!

**Comment by nilsmehlhorn** [comment]
> I inserted your code in my repository (here), but unfortunately it's not working:
core.js:5980 ERROR TypeError: Cannot read property 'undoable' of undefined. 

Yea, initially there's no history until any patches are recorded. I'll update the selector for that case.

> I figured out, that the key in that line is still "DEFAULT" but not the key of the active list.

Right, the selector should probably use the segmenter and end up with "DEFAULT" when it has not been overriden instead of going for that key directly. I'll see how I can integrate that.

Thanks already for your help!

**Comment by nilsmehlhorn** [comment]
Fixed both issues in https://github.com/nilsmehlhorn/ngrx-wieder/pull/29/commits/4c9d533e8966327ddf6955a565711383d6c6bae5 

I've also created a branch in the example repository where everything seemed to be working
https://github.com/nilsmehlhorn/ngrx-wieder-example/commit/653c60dfb90cf2017c1bd3cc0c8c154e857ba310

I'll still add dedicated tests for the selector soon.

**Comment by julianpoemp** [comment]
I tested it on your ngrx-example repository within an effect. It works very well, thank you very much!

I'll give it a try in my application where I'm implementing redo & undo using ngrx-wieder. Currently I'm using my easy approach (just saving whole state to database without considering the undone/redone action).

Here is the effect I created for the ngrx-example in order to test if it's working:

```typescript
import {Injectable} from '@angular/core';
import {Actions, createEffect, ofType} from '@ngrx/effects';
import {Action, createAction, Store} from '@ngrx/store';
import {map, withLatestFrom} from 'rxjs/operators';
import {History} from 'ngrx-wieder';
import * as AppStore from './store';
import {State} from './store';

@Injectable({
    providedIn: 'root'
})
export class AppEffects {
    undoSuccess = createAction('UNDO SUCCESS');
    redoSuccess = createAction('REDO SUCCESS');

    undoRedo$ = createEffect(() =>
        this.actions$.pipe(
            ofType(createAction('UNDO'), createAction('REDO')),
            withLatestFrom(this.store$.select((state: State) => state.app.histories[state.app.activeList])),
            map(([action, history]: [Action, History]) => {
                if (action.type === 'UNDO') {
                    const [undoneStep] = history.undone

                    console.log(undoneStep?.action?.type) // type of action that was undone
                    console.log(undoneStep?.patches) // applied patches

                    // do something e.g. saving to database

                    return this.undoSuccess();
                } else if (action.type === 'REDO') {
                    const [redoneStep] = history.undoable;

                    console.log(redoneStep?.action?.type) // type of action that was redone
                    console.log(redoneStep?.patches) // applied patches

                    // do something e.g. saving to database

                    return this.redoSuccess();
                }
            })
        )
    );

    constructor(
        private actions$: Actions,
        private store$: Store<AppStore.State>
    ) {
    }
}
```

**Comment by alexfarrugia** [comment]
hi @nilsmehlhorn and many thanks for the update and for your comments. Since i had last experimented with ngrx-wieder i have migrated my Store to using ngrx-entity and consequently using EntityState instead of the 'vanilla' state, and it seems like i am not able to wrap my reducer in the createUndoRedo config. Am i doing something wrong or will this not work with EntityState? If so don't worry i will create a test application to test it out. thanks

**Comment by nilsmehlhorn** [comment]
@alexfarrugia are you trying to use this PR against an entity state or the currently available release? Off the top of my head, I'd say it shouldn't be a problem in either case since @ngrx/entity is pretty non-intrusive (e.g. doesn't work with a meta-reducer). Would you be able to provide a reproduction? If this is unrelated to this PR, feel free to open a new issue.

**Comment by alexfarrugia** [comment]
> @alexfarrugia are you trying to use this PR against an entity state or the currently available release? Off the top of my head, I'd say it shouldn't be a problem in either case since @ngrx/entity is pretty non-intrusive (e.g. doesn't require a meta-reducer). Would you be able to provide a reproduction? If this is unrelated to this PR, feel free to open a new issue.

Hi Niels, apologies for not replying earlier, i was referencing this PR. Anyways i managed to fix the issue by adding histories: Histories to my entity state definition and it seems to be working. I still to test the histories feature properly though. Many thanks for this

**Comment by nilsmehlhorn** [comment]
I've added tests for the history state & selectors. I'd appreciate any reviews, I'll soon add some docs and release this.

**Pull request merged**
