### PR TITLE
build(deps): update to Angular & NgRx 11

### PR DESCRIPTION
**Pull request by nilsmehlhorn**
Update to Angular & NgRx 11

### CODE REVIEW

**Comment by julianpoemp** [comment]
I also got an security alert about immer.js version 7, which you already updated in the main branch. Would it be possible to release these dependency updates in the near future? That would be awesome!

**Comment by nilsmehlhorn** [comment]
This PR specifically is blocked until NgRx 11 is released. The 4.0.2 release bumped immer.js to version 8: https://github.com/nilsmehlhorn/ngrx-wieder/blob/v4.0.2/package.json#L29

Otherwise you can always manually install different versions of peer dependencies in your project - you might end up with a warning though.

**Comment by julianpoemp** [comment]
> This PR specifically is blocked until NgRx 11 is released. The 4.0.2 release bumped immer.js to version 8: https://github.com/nilsmehlhorn/ngrx-wieder/blob/v4.0.2/package.json#L29

NgRx 11 was released just 2 days ago ;)

> Otherwise you can always manually install different versions of peer dependencies in your project - you might end up with a warning though.

You're right! I do that until the next ngrx-wieder with new dependencies was released :)

**Comment by julianpoemp** [comment]
Thank you very much! 🎉

**Pull request merged**
